Ubireader must be installed with poetry install
ReFirmLabs/binwalk pull request #639
Opened 2023-05-25 10:53 UTC by HoxhaEndri

https://github.com/onekey-sec/ubi_reader/blob/main/README.md?plain=1#L31

2023-09-21 22:48 UTC, kdelson approved these changes

2023-09-21 23:37 UTC, kdelson commented
Note this patch does introduce an unspecified dependency on poetry so the `deps.sh` script will fail if users do not already have it installed.

2024-01-04 18:26 UTC, akx requested changes

2024-01-04 18:26 UTC, akx commented on INSTALL.md
> +$ (cd ubi_reader && poetry install)
If `ubireader` _requires_  `poetry install`, it is broken.

This should just be

```suggestion
$ pip install ./ubi_reader
```
to have Pip do the right PEP 621 thing.

2024-01-04 18:26 UTC, akx commented on deps.sh
> +    (cd ubi_reader && poetry install)
```suggestion
    pip install ./ubi_reader
```

2024-09-23 02:01 UTC, closed without merging